"""
Project Umbra Modular Agent Tools Package.
Exposes SERPScanner, PlaywrightStealthScanner, StructuredExtractor,
SuppressionEngine, Statutory Legal Notice Generators, and Form Submission Dispatchers.
"""

from __future__ import annotations

from project_umbra.tools.browser_scanner import (
    PlaywrightStealthScanner,
    build_broker_search_url,
    detect_challenge_dom,
    extract_clean_text,
)
from project_umbra.tools.fixtures import (
    get_mock_serp_findings,
    load_broker_fixture,
    load_serp_fixtures,
    render_broker_fixture,
)
from project_umbra.tools.serp_scanner import SERPScanner
from project_umbra.tools.structured_extractor import (
    DeterministicLocalExtractor,
    GeminiStructuredExtractor,
    HTMLSemanticPreprocessor,
    StructuredExtractor,
)
from project_umbra.tools.suppression_engine import (
    BROKER_REMOVAL_ENDPOINTS,
    DEFAULT_PROACTIVE_BROKERS,
    DISPATCHER_REGISTRY,
    KNOWN_BROKER_REGISTRY,
    PEOPLECONNECT_BRAND_METADATA,
    SIMULATED_BROKER_RESPONSES,
    STATUTORY_COMPLIANCE_DAYS,
    BaseBrokerDispatcher,
    FastPeopleSearchDispatcher,
    LegalNoticeGenerator,
    LegalNoticeType,
    NuwberDispatcher,
    PeopleConnectBrand,
    PeopleConnectDispatcher,
    RadarisDispatcher,
    SuppressionEngine,
    TruePeopleSearchDispatcher,
    WhitepagesDispatcher,
    aggregate_and_deduplicate_profiles,
    build_broker_payload,
    calculate_compliance_deadline,
    create_suppression_receipt,
    format_identity_schedule,
    generate_broker_legal_letter,
    generate_ccpa_notice,
    generate_cryptographic_tracking_hash,
    generate_gdpr_notice,
    generate_master_ccpa_letter,
    generate_master_gdpr_letter,
    generate_peopleconnect_payload,
    generate_tracking_reference,
    map_response_to_status,
    normalize_broker_id,
)

__all__ = [
    "SERPScanner",
    "PlaywrightStealthScanner",
    "build_broker_search_url",
    "detect_challenge_dom",
    "extract_clean_text",
    "StructuredExtractor",
    "HTMLSemanticPreprocessor",
    "DeterministicLocalExtractor",
    "GeminiStructuredExtractor",
    "get_mock_serp_findings",
    "load_broker_fixture",
    "load_serp_fixtures",
    "render_broker_fixture",
    # Suppression & Remediation Tools
    "SuppressionEngine",
    "LegalNoticeGenerator",
    "LegalNoticeType",
    "PeopleConnectBrand",
    "PEOPLECONNECT_BRAND_METADATA",
    "KNOWN_BROKER_REGISTRY",
    "DEFAULT_PROACTIVE_BROKERS",
    "BROKER_REMOVAL_ENDPOINTS",
    "SIMULATED_BROKER_RESPONSES",
    "STATUTORY_COMPLIANCE_DAYS",
    "BaseBrokerDispatcher",
    "TruePeopleSearchDispatcher",
    "FastPeopleSearchDispatcher",
    "RadarisDispatcher",
    "NuwberDispatcher",
    "WhitepagesDispatcher",
    "PeopleConnectDispatcher",
    "DISPATCHER_REGISTRY",
    "generate_ccpa_notice",
    "generate_gdpr_notice",
    "generate_peopleconnect_payload",
    "generate_master_ccpa_letter",
    "generate_master_gdpr_letter",
    "generate_broker_legal_letter",
    "generate_tracking_reference",
    "generate_cryptographic_tracking_hash",
    "calculate_compliance_deadline",
    "map_response_to_status",
    "create_suppression_receipt",
    "format_identity_schedule",
    "normalize_broker_id",
    "aggregate_and_deduplicate_profiles",
    "build_broker_payload",
]
